name: Build and deploy

on:
  push:

jobs:   
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: echo $NODE_ENV
        env:
          NODE_ENV: development

    
