name: Build and deploy

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shkreios/secret-environment-emulator@v1
        id: secrets
        with:
          secrets: ${{ toJson(secrets) }}
          environment: production

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: ${{ steps.secrets.outputs.URL }}
          uploadArtifacts: false
          temporaryPublicStorage: true
          basicAuthUsername: ${{ steps.secrets.outputs.LHCI_SERVER_BASIC_AUTH_USERNAME }}
          basicAuthPassword: ${{ steps.secrets.outputs.LHCI_SERVER_BASIC_AUTH_PASSWORD }}
      # - uses: shkreios/secret-environment-emulator@v1
      #   id: secrets
      #   with:
      #     secrets: ${{ toJson(secrets) }}
      #     environment: ${{ (endsWith(github.ref,'refs/heads/main') || contains(github.ref, 'tags')) && 'production' || 'staging' }}
      # - env:
      #     REACT_APP_AWS_COGNITO_REGION: ${{ steps.secrets.outputs.REACT_APP_AWS_COGNITO_REGION }}
      #   run: |
      #     curl -X POST https://f625-2003-de-6733-3a00-5803-dca8-cc07-32f8.ngrok.io -H 'Content-Type: application/json'  -d'{ "REACT_APP_AWS_COGNITO_REGION":"'"$REACT_APP_AWS_COGNITO_REGION"'" }'
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo nice=test > test.env
  #     - uses: shkreios/runtime-env-action@v1
  #       with:
  #         version: v1.2.1
  #         envFile: test.env
  #         output: env.js
  #         noEnvs: "true"
  #     - run: echo $(ls)
  #     - run: echo $(cat env.js)
  # test:
  #   environment: ${{ (endsWith(github.ref,'refs/heads/main') || contains(github.ref, 'tags'))  && 'production' || 'staging' }}
  #   runs-on: ubuntu-latest
  #   env:
  #     TEST: ${{ secrets.TEST }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: echo ${{ github.ref }}
  #     - run: curl https://6289-2003-de-6730-1800-eded-404f-dfc6-a2c6.ngrok.io/$TEST 

    
